# Generated by Django 5.1.4 on 2025-05-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('signature', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('instance_url', models.URLField(max_length=255)),
                ('salesforce_id', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=50)),
                ('issued_at', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
