# Generated by Django 5.1.4 on 2025-05-23 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_googledrivecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoomToken',
            new_name='ZoomCredential',
        ),
    ]
