# Generated by Django 5.1.4 on 2025-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_bulkresumeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_fit_report',
            field=models.JSONField(blank=True, null=True, verbose_name='Job Fit Report'),
        ),
    ]
