# Generated by Django 5.1.4 on 2025-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_jobapplication_job_fit_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='about',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_mode',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='nice_to_have',
        ),
        migrations.RemoveField(
            model_name='job',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_detailed',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parsed Detailed'),
        ),
    ]
