# Generated by Django 5.1.4 on 2025-09-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_remove_job_about_remove_job_job_mode_and_more'),
        ('jobs', '0002_job_parsedjob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
