# Generated by Django 5.1.4 on 2025-05-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Name of the AI agent capability', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the capability', null=True)),
            ],
            options={
                'verbose_name': 'AI Agent Capability',
                'verbose_name_plural': 'AI Agent Capabilities',
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='agents/logos')),
                ('key', models.CharField(db_index=True, help_text='Unique identifier for the AI agent', max_length=255, unique=True)),
                ('name', models.CharField(db_index=True, help_text='AI Agent Name', max_length=255)),
                ('display_tagline', models.TextField(blank=True, help_text='One line description for users', null=True)),
                ('display_description', models.TextField(blank=True, help_text='User-facing description of the AI agent for platform users', null=True)),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Model type (e.g., GPT-4, Claude, etc.)', max_length=255)),
                ('role', models.CharField(blank=True, help_text='Defines AI role (Assistant, Strategist, etc.)', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Internal description for the AI model (used in prompts)', null=True)),
                ('agent_instructions', models.JSONField(blank=True, default=list, help_text='Custom instructions for the AI agent', null=True)),
                ('agent_knowledge', models.JSONField(blank=True, default=dict, help_text='Shared knowledge across all instances', null=True)),
                ('tools', models.ManyToManyField(blank=True, help_text='External Tools', related_name='ai_agents', to='tools.aiagenttool')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
            },
        ),
        migrations.CreateModel(
            name='AIAgentInstance',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_instance_knowledge', models.JSONField(default=dict, help_text='Personalized knowledge for this instance')),
                ('agent_instance_instructions', models.JSONField(default=list, help_text='Task-specific modifications for this AI Agent instance', null=True)),
                ('ai_agent', models.ForeignKey(help_text='Reference to the original AI Agent', on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ai_agents.aiagent')),
            ],
            options={
                'verbose_name': 'AI Agent Instance',
                'verbose_name_plural': 'AI Agent Instances',
            },
        ),
    ]
