# Generated by Django 5.1.4 on 2025-05-30 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentinstance',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace where this AI agent instance is used', on_delete=django.db.models.deletion.CASCADE, related_name='ai_agent_instances', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='capability',
            name='ai_agent',
            field=models.ForeignKey(help_text='The AI Agent this capability belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='ai_agents.aiagent'),
        ),
        migrations.AlterUniqueTogether(
            name='capability',
            unique_together={('name', 'ai_agent')},
        ),
    ]
