# Generated by Django 5.1.4 on 2025-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='dark_avatar',
            field=models.ImageField(blank=True, help_text='Dark mode avatar for the AI agent', null=True, upload_to='agents/logos'),
        ),
    ]
