# Generated by Django 5.1.4 on 2025-06-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_aiagent_dark_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='is_testable',
            field=models.BooleanField(default=False, help_text='Allow this agent to be used in test mode'),
        ),
    ]
