# Generated by Django 5.1.4 on 2025-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0004_aiagent_is_testable'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentinstance',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this agent instance is a demo instance'),
        ),
    ]
