# Generated by Django 5.1.4 on 2025-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0005_aiagentinstance_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this agent is active'),
        ),
        migrations.AddField(
            model_name='aiagent',
            name='mode',
            field=models.CharField(choices=[('under_maintenance', 'Under Maintenance'), ('coming_soon', 'Coming Soon'), ('live', 'Live')], default='live', max_length=255),
        ),
    ]
