# Generated by Django 5.1.4 on 2025-07-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0007_taskexecutionreview_agentreview'),
        ('executions', '0003_alter_taskexecution_ai_agent_instance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskexecutionreview',
            unique_together={('user', 'execution')},
        ),
        migrations.AlterField(
            model_name='agentreview',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='agentreview',
            name='review_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskexecutionreview',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='executions.taskexecution'),
        ),
        migrations.AlterField(
            model_name='taskexecutionreview',
            name='short_feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='taskexecutionreview',
            name='ai_agent_instance',
        ),
    ]
