# Generated by Django 5.1.4 on 2025-07-07 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0008_alter_taskexecutionreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='rating',
            field=models.FloatField(default=0, help_text='Average rating of the AI agent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
