# Generated by Django 5.1.4 on 2025-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0009_aiagent_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Total number of reviews for the AI agent'),
        ),
    ]
