# Generated by Django 5.1.4 on 2025-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0010_aiagent_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for the AI agent', max_length=255, null=True, unique=True),
        ),
    ]
