from django.conf import settings

SALESFORCE_CLIENT_ID = settings.SALESFORCE_CLIENT_ID
SALESFORCE_CLIENT_SECRET = settings.SALESFORCE_CLIENT_SECRET
SALESFORCE_REDIRECT_URI = settings.SALESFORCE_REDIRECT_URI
SALESFORCE_AUTH_URL = settings.SALESFORCE_AUTH_URL
SALESFORCE_TOKEN_URL = settings.SALESFORCE_TOKEN_URL

DEFAULT_SCOPE = "refresh_token api"
