# Generated by Django 5.1.4 on 2025-09-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenrequest',
            name='output_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('analysis', 'AI Analysis'), ('categorization', 'Category Detection'), ('location_mapping', 'Location Mapping'), ('dept_assignment', 'Department Assignment'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('call', 'Emergency Call'), ('booking', 'Appointment Booked'), ('escalation', 'Request Escalated'), ('nearby_search', 'Nearby Services Search'), ('maps_directions', 'Maps Directions Generated'), ('emergency_broadcast', 'Emergency Broadcast Sent'), ('followup_schedule', 'Follow-up Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='citizenrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('police', 'Police'), ('fire_brigade', 'Fire Brigade'), ('ambulance', 'Ambulance/Medical Emergency'), ('health', 'Health Department'), ('cybercrime', 'Cybercrime'), ('disaster_mgmt', 'Disaster Management'), ('other', 'Other/Unsupported Department')], max_length=32),
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('police', 'Police'), ('fire_brigade', 'Fire Brigade'), ('ambulance', 'Ambulance/Medical Emergency'), ('health', 'Health Department'), ('cybercrime', 'Cybercrime'), ('disaster_mgmt', 'Disaster Management'), ('other', 'Other/Unsupported Department')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('analysis', 'AI Analysis'), ('categorization', 'Category Detection'), ('location_mapping', 'Location Mapping'), ('dept_assignment', 'Department Assignment'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('call', 'Emergency Call'), ('booking', 'Appointment Booked'), ('escalation', 'Request Escalated'), ('nearby_search', 'Nearby Services Search'), ('maps_directions', 'Maps Directions Generated'), ('emergency_broadcast', 'Emergency Broadcast Sent'), ('followup_schedule', 'Follow-up Scheduled')], max_length=20),
        ),
    ]
