# Generated by Django 4.2.17 on 2025-01-06 22:33

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, max_length=1000, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='Profile/profile_image'),
        ),
    ]
